### ISSUE TITLE
Pertaining to the Instruction Decoder...

### ISSUE THREAD

**Issue by skilz80** [simsieg/nandgame-solutions#4]
In your solved solution, it's hard to see where the wiring is going around the input as you have the select16 right on top of it... It's not clear to those who are referring to this as a useful resource.

**Comment by Bimi124** [comment]
Hey!
It seems like THIS
![graphic](https://user-images.githubusercontent.com/64980515/92307739-cce74f00-ef98-11ea-9bc6-60147c6c65be.png)
is the same solution and I think it's much better to see the connections.
It's my Screenshoot and you're free to use it.

**Comment by simsieg** [comment]
Thank you for the hint!
I updated the solution.
